server:
  port: 8080

spring:
  proflle:
    active: local # 디폴트 환경
  freemarker: # resources/templates/ 에서 ftl 파일 찾게 하기 위한 설정
    template-loader-path: classpath:/templates/
    suffix: .ftl
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: govlepel@$&
  social:
    kakao:
      client_id: 9a9a02eedbe752442e4a7550ec217f88
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  redis:
    host: localhost
    port: 6379