logging:
  level:
    root: warn
    com.example.spring: debug

spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hdm2ddl.auto: update
      format_sql: true
    show-sql: true
    generate-ddl: true
  url:
    base: http://localhost:8080